### ISSUE TITLE
Bild/Video läuft zu breit

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/rrze-video#10]
Wenn ich auf das Vorschaubild klicke und sich die Lightbox öffnet, erscheint das Bild zunächst passend im Rahmen. Nach kurzer Zeit läuft es rechts aus dem Rahmen heraus. Nach dem Klick auf Play passt es wieder.
Bitte die Bildgröße hier entsprechend anpassen.

**Comment by mduven** [comment]
Ist mir auch eben aufgefallen, bleibt allerdings auch beim Abspielen so:

![2017-12-06 09_58_59-fachbereich wirtschaftswissenschaften](https://user-images.githubusercontent.com/28564104/33653305-f4ab2410-da6c-11e7-94ac-b44985346778.png)

**Comment by bmehler** [comment]
Habe es gerade auch gesehen.
Es liegt sehr wahrscheinlich an dem WP Update auf 4.9.
