### ISSUE TITLE
Titel bei Genre übernehmen

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/rrze-video#11]
Wenn ich über das Widget ein Zufallsvideo im Footer einbinde, wird der allgemeine Titel angezeigt, der im Widget angegeben ist. 
Schöner/Sinnvoller ist es jedoch, wenn der Titel des tatsächlichen Videos, welches per Zufall ausgewählt wird, übergeben wird und angezeigt wird. Sonst benötigen wir einen sehr allgemeinen Titel, wie z.B. "Zufallsvideo"

**Comment by bmehler** [comment]
gelöst - wurde mit der Version 1.2.11 eingespielt.
