### ISSUE TITLE
Thumbnailgrößen sind unterschiedlich zwischen fau.tv und youtube

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/rrze-video#118]
<img width="818" alt="image" src="https://github.com/RRZE-Webteam/rrze-video/assets/9526974/673c42bb-2ad8-411d-aa67-51b002eb816a">
Videos danach haben die gleiche Größe, nur die Thumbnails nicht - festgestellt in Chrome Version 114

**Comment by lukasniebler** [comment]
Ich denk fast die beste Lösung wäre, den Shortcode um ein weiteres Attribut zu erweitern, welches Erlaubt die Aspect-Ratio festzulegen.

Ansonsten werden die schwarzen Balken vom Image-Film noch größer, wenn ich als Default 16/9 festlege.

**Comment by lukasniebler** [comment]
Dann könntest du den FAU Imagefilm z.B. auf eine Aspect-Ratio von 2.40/1 stellen und erhältst dann diese Ausgabe:
<img width="1434" alt="Bildschirmfoto 2023-06-28 um 17 16 20" src="https://github.com/RRZE-Webteam/rrze-video/assets/58593037/659efc19-5d63-4178-8796-84306dea2606">
@wrcg

**Comment by lukasniebler** [comment]
Feature in nächster Version verfügbar. (Vermutlich verfügbar in 1-2 Wochen)
