### ISSUE TITLE
Endpoint entfernen oder Index machen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-video#12]
Der Endpoint /video ist erreichbar, genauso wie der Endpoint der einzelnen Videos.
Dies entweder wegmachen oder aber den Content für die Bereiche entsprechend
erstellen.
https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/303#issuecomment-371988893

> ...betrifft die Videoübersicht für Videos aus der Videothek (https://geographie.cms.rrze.uni-erlangen.de/video/)
> 
> Wenn ich über dieses Menü zum Beispiel die "Video-Anhangseite" https://geographie.cms.rrze.uni-erlangen.de/video/wie-entstehen-unterschiedliche-stadtviertel/ auswähle, erscheint nichts im content.
> 
> Ist dieser Fehler bereits bekannt? (getestet mit Chrome)

**Comment by Albager** [comment]
Ich persönlich finde diesen Video-Endpoint eigentlich praktisch und er sollte m. E. im Einrichtungen-Theme erhalten bleiben, sofern die Endpoints der einzelnen Videos dann auch funktionieren.

**Comment by xwolfde** [comment]
Also schöner machen.

**Comment by xwolfde** [comment]
Die Index- bzw. die Einzeldarstellung der Custom Posts fehlt noch @iamwebrocker ? 

Also beim Aufruf der Testsite einerseits mit /video und dann bei Klick auf einem Video aus dem Index andererseits.

**Comment by iamwebrocker** [comment]
hm, aber das ist doch Sache des Themes, nicht des Plugins, wie die Single- bzw Archive Sachen der Cusotmposttypes ausgegeben werden?

**Comment by xwolfde** [comment]
Ne, das Theme kann ja nicht alle möglichen Plugins kennen. Zudem würde man dann diese Funktion nur für das jeweilige Theme optimieren, während es bei dem Einsatz mit anderen Themes Probleme gäbe.
Man muss also ein eigenes Template, bzw zwei (Index + Einzelseite) ablegen.


_If using a plugin, you need to create archive-my_custom_post_type.php or  single-my_custom_post_type.php in plugins's folder and point wordpress to read it, so include this function in your plugin:_ 

```

function get_custom_post_type_template($template) {
    global $post;

    if ($post->post_type == 'my_custom_post_type') {
        $template = dirname( __FILE__ ) . '/archive-my_custom_post_type.php';
    }
    return $template;
}

//add_filter( "single_template", "get_custom_post_type_template" ); //for single page
add_filter( "archive_template", "get_custom_post_type_template" ); //for archive
```

**Comment by iamwebrocker** [comment]
ok, schaue ich mir an.

**Comment by iamwebrocker** [comment]
@xwolfde hm, kollidiert das nicht mit
https://github.com/RRZE-Webteam/rrze-video/blob/master/includes/endpoint/video-endpoint.php#L49
?
(bin gerade etwas verwirrt, warum macht Ihr dort am Endpoint mit expliziten Themes rum, für die dann explizite Templates bereitgestellt werden? DAS wäre doch tatsächlich Hoheit der jeweiligen Themes?) Der von Dir zitierte Ansatz hookt ja generell in "single" bzw "archive" Template handling, wenn der Posttype passt -- das würde dann wiederum das Template handling da im endpoint code aushebeln?

**Comment by xwolfde** [comment]
fixed
