### ISSUE TITLE
Neues Videoportal und URLs

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-video#14]
Wenn ich mir die URL eines Clips vom Videoportal kopiere, dann lautet dei URL in der Adresszeile
zum Beispiel so:
https://www.video.uni-erlangen.de/clip/id/6107

Wenn ich dies im Player als WIdget oder als Video-Custum Type eintrage, funktioniert es nicht!

Stattdessen muss man die URL händisch in
https://www.video.uni-erlangen.de/webplayer/id/6107
ändern.

Das ist knorke und nicht Sinn der Sache. oembed sollte doch gerade mit der URL funtionieren die im Browser angezeigt wird.
Das muss entweder im Videoportal gefixt werden oder aber wir bauen hier im Plugin eine automatisch Ersetzung und Korrektur der URL ein..

**Comment by xwolfde** [comment]
Also irgendwas klappt da überhaupt nicht mit dem neuen Videoportal...

Hier zu sehen (unten):
https://www.beta.wordpress.rrze.fau.de/

**Comment by Albager** [comment]
ja, das habe ich auch schon festgestellt... Habe nicht rausgefunden, wie man es hinbekommt... Sollte man nicht eigentlich auch nur die ID (also ohne URL) angeben können, wenn es sich um ein Video aus dem FAU-Videoportal handelt?

**Comment by xwolfde** [comment]
"Einst" hat diese Oembed-URL wohl funktioniert:
"https://www.video.uni-erlangen.de/services/oembed/?url=https://www.video.uni-erlangen.de/clip/id/9478"

diese leitet aber jetzt zunächst um auf
https://itunes.video.uni-erlangen.de/services/oembed/?url=https://www.video.uni-erlangen.de/clip/id/9478

und dann kommt da eine kaputte Website und kein Video und erst recht keine REST-Ausgabe :(

**Comment by xwolfde** [comment]
Die korrekte Aufrufs-URL zum JSON lautet:

http://www.video.uni-erlangen.de/services/oembed/?url=$URL&format=json


Also bei dem Video
https://www.video.uni-erlangen.de/clip/id/9479
" 8-Inclusive Javascript	"

ist die URL zum JSON genau diese:
https://itunes.video.uni-erlangen.de/services/oembed/?url=https://www.video.uni-erlangen.de/clip/id/9479&format=json
