### ISSUE TITLE
Video-Beschreibungen: Abweichende Darstellung RRZE-Video Widget im Social Media Footer vs. Shortcode im Content

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/rrze-video#15]
Auf der Seite https://geographie.cms.rrze.uni-erlangen.de/studium/studieninteressierte/ habe ich Videos per Shortcode `[fauvideo id="20318" width="210" youtube-support="1" showtitle="2"]` eingefügt. Dort wird die Videobeschreibung im Popup korrekt formatiert angezeigt:

![rrzevideo_descriptionok](https://user-images.githubusercontent.com/11389126/37560079-f2afc0e8-2a31-11e8-8014-d3bda8885f9e.PNG)

Testhalber habe ich mal den Social Media Footer auf der Startseite angeschaltet und dort das selbe Video mittels RRZE-Video Widget platziert. Im Popup ist die Videobeschreibung nicht korrekt formatiert, sondern ab der Hälfte umgebrochen. Bug?

Außerdem unterscheiden sich die Textformate und der Umbruch der Überschrift ist (in beiden Versionen) unschön.

![rrzevideo_description](https://user-images.githubusercontent.com/11389126/37560087-1ee10ffa-2a32-11e8-99c5-deb0abbd1a3e.PNG)

**Comment by iamwebrocker** [comment]
@xwolfde Ihr macht im Theme Selektoren mit ID drin; diese überschreiben aufgrund der höheren Spezifität die Anweisungen, die das Videomodal Styling betreffen, da das Modal im Context der Social Widgets eingebunden ist. ```#social .textwidget, #social p, #social h2.small, #social h2 { ... }``` "gewinnt" dann und daher sehen die beiden Modals Shortcode und Widget unterschiedlich aus. Ich habe im Zuge des Umbaus ein paar "!important" Anweisungen in das rrze-video.css reingenommen, die das nun überschreiben -- halte das aber nur für eine Interimslösung; eigentlich müssen die ID-basierten Selektoren raus aus dem Haupttheme.
