### ISSUE TITLE
Links in Videobeschreibungen

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/rrze-video#16]
Es wäre toll, wenn man im Textfeld der Videobeschreibungen Links mit `<a href=...>` setzen könnte (im Beispiel gewünscht wäre ein Link auf meinstudium.fau.de). Momentan wird HTML aus der Eingabe beim Speichern automatisch entfernt.

![rrzevideo_descriptionlinks](https://user-images.githubusercontent.com/11389126/37560260-5a679a6e-2a35-11e8-94d5-800747f7289a.PNG)

**Comment by xwolfde** [comment]
Geht noch nicht. HTML wird entfernt.

**Comment by iamwebrocker** [comment]
Yep. Braucht Umbau der Metabox plus Modifikation, dass diese den WP-JS WYSIWYG Editor zulässt, dann noch entsprechende Content-Filter bei der Ausgabe. Falls ich das machen soll, bitte Bescheid geben.

**Comment by xwolfde** [comment]
jupp. passt
