### ISSUE TITLE
Core Fehler wegen 404

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-video#167]
Bei einigen Videos wird versucht die vtt Datei zu laden. Hier kommt allerdings ein 404.
(Was auch stimmt)

Beispiel URL:
https://www.muster-fakultaet.wordpress.rrze.fau.de/studiengang/hebammenwissenschaft-bsc/

liefert u.a.:
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://cdn2.fau.tv/symlinks/959f3a8a-1d7e-41db-8d8b-400508c32979.vtt. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt). Statuscode: 404.

https://cdn2.fau.tv/symlinks/959f3a8a-1d7e-41db-8d8b-400508c32979.vtt liefert in der Tat 404.

Wo kommt diese URL-Anfrage her? ggf. liefert das FAU.TV eine falsache URL aus dem oembed?

**Comment by lukasniebler** [comment]
Behoben durch Stefanos
