### ISSUE TITLE
Fehlende strukturierte Daten

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-video#195]
Bitte mal schauen ob wir uploadDate und thumbnailUrl ergänzen können.

<img width="611" alt="grafik" src="https://github.com/RRZE-Webteam/rrze-video/assets/1070669/40fd65c2-df8e-459d-a384-d0d271105128">

**Comment by xwolfde** [comment]
Problem ist noch offen und betrifft alle Seiten.
<img width="937" alt="grafik" src="https://github.com/RRZE-Webteam/rrze-video/assets/1070669/c0c43b8d-3af4-483f-b55c-95e5ca3744a3">

**Comment by lukasniebler** [comment]
Prüfen für v5.1

**Comment by lukasniebler** [comment]
Bereits in v5 behoben
