### ISSUE TITLE
JS und CSS-Konflikte

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-video#2]
Das Plugin verursacht durch das JS und das CSS Konflikte mit anderen Skripten, insbesondere der Bühne.

vgl auch: https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/253: 
"Zusätzlich zum zu hohen Titel fehlt u.a. auf https://www.wiso.rw.fau.de/ die Schaltfläche, um die Slides weiterzuklicken. Es bleibt auch immer beim Ersten. Bei den Seiten, die ich betreue, betrifft das jeweils die, bei denen der Expertenmodus ausgewählt ist. Auf https://www.rw.fau.eu/ ist alles wie zuvor, hier ist der normale Modus aktiv."

**Comment by ec89yler** [comment]
Hallo, wollte kurz hören, ob es hier schon Neuigkeiten gibt? VG

**Comment by bmehler** [comment]
Das Plugin wird derzeit noch getestet. VG

**Comment by ec89yler** [comment]
Hallo, habe heute die neue Version aktiviert, um https://github.com/RRZE-Webteam/FAU-RWFak/issues/39 entsprechend umzusetzen, was nun auch ohne Beeinträchtigung der Bühne funktioniert. Allerdings, wenn ich nun Links (z.B. auf der Startseite einen Beitrag oder Punkte in den Portal-Menüs) anklicke, wird zunächst automatisch zum Seitenanfang zurückgescrollt. Dies passiert ebenfalls, wenn ich auf https://www.wiso.rw.fau.de/fachbereich/kommunikation-und-marketing/medienportal/multimedia/ das Accordion aufklappe. Hier muss man dann jedes Mal erneut nach unten scrollen. Liegt wohl am Video-Plugin, da dies nicht mehr der Fall ist, wenn ich es deaktiviere. Würdet Ihr Euch das mal ansehen? Vielen Dank.

**Comment by ec89yler** [comment]
Hier noch analog ein Accordion auf einer anderen Seite: https://www.fbv.rw.fau.de/service/beschaeftigte/

**Comment by bmehler** [comment]
Hallo, danke für das schnelle Feedback.
Selbstverständlich werde ich den Bug beheben.
VG

**Comment by bmehler** [comment]
Hallo, wurde soeben von mir gefixt.
Nun sollte bei einem Klick auf einen Link oder auf das Accordion nicht mehr zurückgescrollt werden.
VG

**Comment by mduven** [comment]
Sieht gut aus, Danke! :) VG
