### ISSUE TITLE
Anzeige im Social Media Footer

### ISSUE THREAD

**Issue by mduven** [RRZE-Webteam/rrze-video#22]
Haben im Social Media Footer 3 Videos mit gleichen Einstellungen eingebunden, die plötzlich unterschiedlich angezigt werden:

![2018-10-17 10_30_25-fachbereich wirtschaftswissenschaften](https://user-images.githubusercontent.com/28564104/47074244-4be30b00-d1fa-11e8-954a-a995fca88359.png)

Scheint auf fau.de auch so zu sein..

**Comment by xwolfde** [comment]
Ja, sind YouTube-Videos.
Ref #24 

Muss gefixt werden.
