### ISSUE TITLE
wpautop(🪤) – Nutzung im Alert führt zu einem Einfügen von ```<br>``` und ```<p>```-Tags

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-video#228]
- Die VIdeometa in Elements-Alert wird als block angezeigt was dazu führt, dass ein riesiger Abstand entsteht…
Prüfen.

**Comment by migrosch** [comment]
Dieses Problem liegt m.E. daran, dass die enthaltenen META-Elemente unter bestimmten Umständen durch `<br />`s getrennt werden.

Beispiel 1 (mit Abstand): https://www.intern.fau.de/blog/ (unter "Neues von Menschen aus der FAU")
![Bildschirmfoto 2024-09-09 um 09 47 00](https://github.com/user-attachments/assets/53d052d4-ede2-433f-9e84-466e6400ae81)

Beispiel 2 (ohne Abstand): https://www.fau.de/outreach/wissenschaft-fuer-buergerinnen-und-buerger/ (unter "Universitätstage")
@
![Bildschirmfoto 2024-09-09 um 09 47 46](https://github.com/user-attachments/assets/bd84bd43-ebf6-4295-9d62-2842987b2644)

Ich hoffe, das hilft beim Debugging.

**Comment by lukasniebler** [comment]
@xwolfde – Das sieht mir wieder nach einem wp-autop Problem aus z.B. im Elements-Alert. 
Kann ich das Meta-DIV einfach mit CSS verstecken? Mit ```display:hidden``` könnte ich es ausblenden… Bin mir aber nicht sicher, ob die Umbrüche trotzdem bei Google Probleme verursachen…

Beispiel auf https://www.fau.de/newsportal im Alert.
<img width="507" alt="Bildschirmfoto 2024-09-09 um 10 33 48" src="https://github.com/user-attachments/assets/a3b1ab78-de62-4c51-b53a-d2d6c415fd5b">

**Comment by xwolfde** [comment]
Das kann man zwar so machen, löst aber das ursächliche Problem nicht...

ggf. sollte der Alert Bereich da einfach gefixt werden, wenn dieser das Problem verursacht?

**Comment by migrosch** [comment]
Übrigens ist das Problem neu und war "früher" nicht da. 🤷‍♂️

**Comment by cassandre** [comment]
Lag tatsächlich am Alert. Ist jetzt gefixt. Vgl. https://github.com/RRZE-Webteam/rrze-elements/issues/339

**Comment by migrosch** [comment]
Wann wird der Fix auf https://www.intern.fau.de/ ausgerollt? Auf https://www.intern.fau.de/blog/ (unter "Menschen aus der FAU") sind die Abstände nämlich noch zu sehen. Oder ist das ein Cache-Problem? Oder womöglich ein anderes Problem, da dort "RRZE Elements" gar nicht installiert ist? Warum eigentlich?

**Comment by lukasniebler** [comment]
@migrosch Auf dem CMS läuft seit eben die neuste Elements-Version. Der Fehler sollte jetzt behoben sein. Man sieht Elements nicht in der Plugin-Übersicht, da es Netzwerkweit aktiviert ist. Ist also in den Plugin-Übersichten für Seiten-Admins ausgeblendet, damit es nicht aus Versehen deaktiviert wird.

**Comment by lukasniebler** [comment]
Anscheinend ähnliches Problem bei Nutzung in Columns? Am Montag prüfen

**Comment by lukasniebler** [comment]
Super, danke
