### ISSUE TITLE
PHP-Fehler (ltrim()) bei fauvideo-Shortcode

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/rrze-video#235]
Auf Seiten, auf denen ich einen fauvideo-Shortcode einbinde, bekomme ich die Fehlermeldung: 

Deprecated: ltrim(): Passing null to parameter #1 ($string) of type string is deprecated in ...wp-includes/formatting.php on line 4482

**Comment by lukasniebler** [comment]
Falls jemand einen Tipp hat, woher die Deprecated Warnung kommt… Gerne melden. Bis jetzt hab ich noch nicht rausgefunden, wo genau der Auslöser steht…
