### ISSUE TITLE
Play-Button bei YouTube-Videos defekt

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-video#24]
Im Widget ist der PLay-Button falsch, wenn es ein YouTube Video ist

![rrze-video-youtube-play](https://user-images.githubusercontent.com/1070669/47563827-55b7ed00-d923-11e8-92e7-d97587761505.png)

**Comment by iamwebrocker** [comment]
Hi, in 1.2.19 geht das noch - habe gerade die 1.3.1 lokal aktiviert, dann ist der button falsch.
ich habe noch nicht tiefer gegraben, aber anscheinend gibt es für die `.overlay-widget` klasse, die das icon umschliesst, kein styling.
gerade mal auf die schnelle in den dev-tools das hier eingebaut:

```
.overlay-widget {
    position: absolute;
    top: 50%;
    left: 50%;
    color: #fff;
    text-align: center;
    display: flex;
    transform: translate(-50%,-50%);
    font-size: 5em;
    opacity: 0.7;
}
```
dann sieht das play icon ok aus (siehe anhang)
![rrze-widget](https://user-images.githubusercontent.com/1223080/48266966-419ae200-e431-11e8-85ba-41f9c5e2b6f9.png)

**Comment by iamwebrocker** [comment]
hm, anscheinend greift das hier: https://github.com/RRZE-Webteam/rrze-video/blob/master/assets/css/sass/_base.scss#L217 nur in `.rrze-video-widget-box`, im Markup landet aber `.rrze-widget-container`

**Comment by xwolfde** [comment]
fixed
