### ISSUE TITLE
Externer Code ist nach Modalklick laden

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-video#3]
Wie gerade besprochen:

Externe Daten/HTML/JS-Codes sollten erst geladen werden, nachdem man das Modal aufruft.

Sprich. Per default wird beim Laden der Seite noch keine Verbindung zu den Videoportal/YouTube oder anderen Videoprovider aufgebaut, sondern nur das Artikelbildes Custom Post Types gezeigt. Erst wenn man dann auf den Link zum Video klickt, wird erst dann mit einem Ajax-Request der notwendige Code geholt.

Ziel ist also, daß beim Laden der gesamten Website noch kein Request auf YouTube und co gemacht wird.

**Comment by bmehler** [comment]
Ist erledigt.

**Comment by bmehler** [comment]
Hab noch Bugs gefunden.
