### ISSUE TITLE
Auflösung und Anzeige der Thumbnails prüfen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-video#31]
Aus Feedback:

Das Vorschaubild beim Einbinden in Seiten/Meldungen ist nicht ganz scharf: 

Beispiel https://www.fau.de/studium/studienbeginn/semesterticket/ 
[fauvideo url="https://www.youtube.com/watch?v=VDSJBAgcS2g"] - ich glaube das Problem tritt nur bei Youtube-Videos auf, nicht bei FAU-Videoportal-Videos. 

Hier kann man den Vergleich gut sehen (keine Ahnung warum das Video zwei Mal drin ist): https://www.fau.de/alumni/veranstaltungen-und-termine/ehrungen-von-promovierten-und-jubilaren/ 
[fauvideo url="https://www.video.uni-erlangen.de/webplayer/id/34917" showtitle="1"] 
[fauvideo url="https://youtu.be/_HHT9zEmrwc" width="640" height="360" youtube-resolution="4" youtube-support="0" showtitle="0"]

Und im Footer auf der Startseite lassen sich Youtube-Videos einbinden (nicht nur FAU-Videoportal-Videos), aber dann ist das Thumbnail größer als die anderen (dafür hab ich kein Beispiel).

**Comment by iamwebrocker** [comment]
ich habe eine allgemeine funktion zur anzeige der previews etabliert, die nun sowohl von widget als auch vom shortcode genutzt wird ( https://github.com/RRZE-Webteam/rrze-video/blob/dev/includes/functions/rrze-video-functions.php#L9 ). wegen responsive darstellung kann es aber vorkommen, dass ein redakteur zb die yt auflösung für ein kleines thumbnail wählt, aber in einem der breakpoints dieses bild etwas hochskaliert wird, um die umgebende box zu füllen, was dann die beschriebene unschärfe erklären würde und warum das nur bei yt auftritt.

**Comment by xwolfde** [comment]
tut & ist gut.
