### ISSUE TITLE
Videothek: Quickedit-Bearbeitung löscht Eingaben

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/rrze-video#35]
Wenn man in der Videothek-Übersicht über Quickedit etwas ändert, werden beim Aktualisieren die URL und die Beschreibung des Videos gelöscht.

**Comment by xwolfde** [comment]
Stimmt, das Problem ist noch vorhanden.  
Das Quickedit ermöglicht eh nur das ändern der Kategorie. Kann man darauf nicht komplett verzichten und es ganz disablen?

**Comment by xwolfde** [comment]
Auch das Artikelbild wird weggemacht :(

**Comment by xwolfde** [comment]
Dieser Issue wird aus den Milestone und damit dem Auftrag entfernt.

**Comment by xwolfde** [comment]
In der neuen version wird es diese Option nicht mehr geben :=P
