### ISSUE TITLE
Default Breite / Höhe des Videos im Modal in settings konfigurierbar machen

### ISSUE THREAD

**Issue by iamwebrocker** [RRZE-Webteam/rrze-video#37]
Momentan ist 640 / 360 an mehreren Stellen im Code (php und js) hart reingeschrieben.
Es könnte m.E. relativ einfach in die Settings des Plugins umziehen und dort bei Bedarf verändert werden.

**Comment by xwolfde** [comment]
Ja, bitte machen, wenn es in der Zeit reinpasst

**Comment by xwolfde** [comment]
Ja, diesen hardcodierten Mist, der auf 640px rückspringt, rausnehmen:

rrze-video-shortcode.php:

```php
    // warum?
    if ( preg_match("/^[a-zA-Z.:\/ ]*$/", $width_shortcode, $matches ) ) {
        $width_shortcode = 640;
        $suffix = 'px';
    } elseif ( preg_match("/(\d+)%/", $width_shortcode, $matches ) ) {
        $width_shortcode = 640;
        $suffix = 'px';
    } else {
        $suffix = 'px';
    }

```

**Comment by xwolfde** [comment]
fixed. ggf. noch relikte im code, die aber nichts mehr machen

**Comment by iamwebrocker** [comment]
Es ist im JS-code noch hart drin, der das Modal macht - falls Bedarf besteht, dies über das Plugin-Setting zu steuern, sag nochmal Bescheid.

https://github.com/RRZE-Webteam/rrze-video/blob/master/includes/ajax/rrze-video-player-js.php#L62
