### ISSUE TITLE
Abwärtskompatibilität: YouTube-Videos in Videothek

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-video#41]
Wir haben ein problem hinsichtlich der Abwärtscompatibilität:

Ist in der Videothek ein YouTube-Video eingetragen (ohne Thumbnail), wird
es bei Nutzung des  Videos im WIdget (dort ANgabe über ID statt über URL)
![rrze-video-widget-problem-videothek-20190311](https://user-images.githubusercontent.com/1070669/54120580-58117400-43f8-11e9-8521-449914f19356.png)

zu klein dargestellt.

![rrze-video-widget-problem-videothek-display-20190311](https://user-images.githubusercontent.com/1070669/54120588-5cd62800-43f8-11e9-884b-90be337fb663.png)

**Comment by xwolfde** [comment]
Hier nochmal ein Beispiel:
WIdget:
![2019-03-18-09-17-www wiso rw fau de](https://user-images.githubusercontent.com/1070669/54516848-66afdc00-4960-11e9-9014-a800076d8683.png)

Mediathek:
![2019-03-18-09-18-www wiso rw fau de](https://user-images.githubusercontent.com/1070669/54516857-6d3e5380-4960-11e9-90cf-86afb65a7b84.png)


Könnte es mit dem JavaScript zusammenhängen? Das bei der ANzeige noch ein altes verwendet wurde?

**Comment by iamwebrocker** [comment]
Hm… mir fällt da nur ein/auf, dass wir das "ID" ja abgeändert haben von input zu einem select… ich schaue mir das an, was da passiert, aber eigentlich dürfte das keine auswirkung haben, denn auch beim select wird als option-value nur die ID mit übergeben.
