### ISSUE TITLE
Keine Vorschaubilder im Social Media Footer/Widget? (und andere Problemchen)

### ISSUE THREAD

**Issue by Albager** [RRZE-Webteam/rrze-video#46]
Wenn man das RRZE Video Widget im Social Media Footer platziert, werden keine Vorschaubilder angezeigt. Habe es mit einem Video aus der Videothek und einem aus externer Quelle probiert (das Speichern der Einstellungen funktioniert btw auch nicht richtig, es springt bei Klick auf  "Speichern" immer zurück auf "externe Quelle", sobald da was drin steht -> evtl. neuer Issue?).

Siehe Screenshot:

![image](https://user-images.githubusercontent.com/11389126/59378448-9e0e0900-8d54-11e9-8f4c-65a14205b475.png)

![image](https://user-images.githubusercontent.com/11389126/59378476-a9f9cb00-8d54-11e9-8f24-bf7333225552.png)

Das Verhalten ändert sich zwar, wenn man in der Videothek für das betreffende Video manuell ein Beitragsbild einstellt. Aber bisher ging / im Popup geht es ja auch automatisch mit dem Vorschaubild von youtube. Siehe Screenshot von https://www.geographie.nat.fau.de/ im Social Media Footer nicht ok:
![image](https://user-images.githubusercontent.com/11389126/59378203-11634b00-8d54-11e9-83ad-2c10cd463d8a.png)
Im Popup alles ok:
![image](https://user-images.githubusercontent.com/11389126/59380823-39ee4380-8d5a-11e9-9434-043d64df9e7a.png)

Im rechten Teil des Screenshots ist das andere Video-Widget zu sehen, bei dem das Vorschaubild automatisch von youtube geladen wird. Hier ist jedoch die Formatierung der Steuerelemente nicht ideal und kann wohl auch nicht weiter angepasst werden (-> evtl. neuer Issue?).

**Comment by xwolfde** [comment]
Du hast kein Häckchen bei den Vorschaubildern :)
![grafik](https://user-images.githubusercontent.com/1070669/59385817-770c0300-8d65-11e9-8005-832af073109c.png)

Ansonsten gibt es leider ein Problem mit in der Vorversion von FAU Video eingestellten Parametern des Widgets, die damals falsch gespeichert waren. 
Ebenso gibt es  Probleme damit, dass der Browser (! und nicht unser Skript) Videos derzeit blockiert, wenn sie von einer fremden Domain kommen. Hier sind wir dran, noch was mit einem  Headertag zu machen.

**Comment by iamwebrocker** [comment]
Sollten wir das Häckchen per default setzen? Aus Datenschutz wäre ich dagegen, aber gerade bei Legacy-Einbindungen ist das … intransparent, dass sich das nun dort "versteckt".

**Comment by iamwebrocker** [comment]
Komisch finde ich auch, dass das Video selbst so klein im Modal ist - bei unseren Tests waren die volle Breite im Modal. Sind die dort zu sehenden 300px der Browser-Default-Wert für Iframes ohne explizite Breitenangabe?

**Comment by xwolfde** [comment]
Ich bin auch dagegen. Die Leute sollen das bewusst einschalten. Ggf. würde ich da sogar noch im Backend den Hinweis ergänzen, dass man mit dem EInschalten dann auch die Pflicht erhält, die eigenen Datenschutzerklärung anzupassen. Aber da werden wir eh noch in unserem Datenschutzgenerator was gesondert machen. Ggf. kommt es da zu einem Automatismus.

**Comment by xwolfde** [comment]
Hm... 300px als Default für iframes wäre schon verdächtig wenig..
Muss ich Freitag mal schauen. Im Theme wurde heute ein Blocker-Bug entdeckt, so daß ich da ran muss...

**Comment by iamwebrocker** [comment]
Ich glaube, wir müssen da im Plugin noch an die Styles ran - wegen Responsive und dem Wegfall von width / height Angaben am iframe selbst muss was mit dem wrapping div position relative und dem iframe dann position absolute und width/height 100% gemacht werden - etwas blöd ist, dass wir zum Zeitpunkt des Ausliefern des codes nicht wissen, welches Seitenverhältnis das wrapping div für den iframe "aufspannen" muss.

**Comment by iamwebrocker** [comment]
... dann sieht es so aus: 
![Bildschirmfoto 2019-06-12 um 23 26 53](https://user-images.githubusercontent.com/1223080/59387505-9a38b180-8d69-11e9-8ef1-8f4917cff77b.png)

**Comment by Albager** [comment]
> Du hast kein Häckchen bei den Vorschaubildern :)
> ![grafik](https://user-images.githubusercontent.com/1070669/59385817-770c0300-8d65-11e9-8005-832af073109c.png)

Wie komme ich denn als Otto normal Admin an die Plugin-Einstellungen? So wie ich das sehe, kann ich das Plugin nur an- oder abschalten.
![image](https://user-images.githubusercontent.com/11389126/59425859-09002400-8dd7-11e9-903b-885b2a608aa4.png)

**Comment by xwolfde** [comment]
Es gibt kein "Plugin-Menu". Manchen Plugins haben einen SItz im Menü, wenn sie Custom Inhalte verwaltbar machen. Aber die Settings von Menüs gehören definitionsgemäß unter den Einstellungen oder unter Werkzeuge,

**Comment by Albager** [comment]
Ich meine diesen Button mit "Einstellungen" oder "Settings"  im "Plugin-Menü", also dort, wo man Plugins an oder ausschaltet:
![image](https://user-images.githubusercontent.com/11389126/59432183-0279a880-8de7-11e9-8433-68c4770948a2.png)
![image](https://user-images.githubusercontent.com/11389126/59432222-1b825980-8de7-11e9-9b95-9a27a7da8c3b.png)
Der ist an dieser Stelle m. E. schon ziemlich praktisch.

**Comment by xwolfde** [comment]
Das ist da nur dann sinnvoll, wenn man nur Admins hätte. Denn nur Admins können die Lasche Plugins sehen und aufrufen. Normalerweise sollte man Redakteuren und Autoren jedoch keine Adminrolle geben. 
Daher müssen für diese User die Einstellungen auch woanders aufindbar sein.

**Comment by Albager** [comment]
> Das ist da nur dann sinnvoll, wenn man nur Admins hätte. Denn nur Admins können die Lasche Plugins sehen und aufrufen.

Jawoll - wenn ohnehin nur Admins die Plugins-Lasche sehen können, dann könnte man den Button zu der etwaigen Plugin-Einstellungsseite da doch bedenkenlos setzen (ist ja nur ein Link zu der Einstellungs-Seite an anderer Stelle). Nur als Anregung.

**Comment by iamwebrocker** [comment]
ich mache mal für den settings link ein eigenes issue

**Comment by Albager** [comment]
Die Vorschaubilder funktionieren wie gewünscht, wenn der Haken im RRZE-Video-Plugin gesetzt wird, siehe [Antwort von xwolfde](https://github.com/RRZE-Webteam/rrze-video/issues/46#issuecomment-501453408). Die Sache mit dem [Settings-Link wurde verschoben](https://github.com/RRZE-Webteam/rrze-video/issues/53), daher mache ich den Issue hier mal zu.
