### ISSUE TITLE
Breite bei Portal/Standardseite und anderen ohne SIdebar und Navi

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-video#47]
Die Max. Breite ist festgelegt auf 640px aufgrund des zur verfügung stehenden Raumes bei Inhaltsseiten mit Navi.

Auch bei anderen SeItentypen sollte die Größe auf 100% gehen.
(Verkleinerung und Zentrierung lässt sich dann durch umrandende divs erreichen)

**Comment by iamwebrocker** [comment]
Hi,

ich sehe drei Stellen, an denen "640" hart gecoded ist:

https://github.com/RRZE-Webteam/rrze-video/blob/master/assets/css/sass/_base.scss#L29
https://github.com/RRZE-Webteam/rrze-video/blob/master/assets/css/sass/_base.scss#L71

https://github.com/RRZE-Webteam/rrze-video/blob/master/includes/ajax/rrze-video-player-js.php#L37

Die beiden im SASS/CSS sind glaube ich die, die Du meinst mit der Maximalbreite, und das liesse sich schnell entfernen.

Ich halte die dritte Stelle, die im JS, für interessanter, denn hier wird geschaut, ab wann das Video in einem Modal aufgehen soll - ausgehend davon, dass das Video sowieso eine maximale Breite hat und daher ein Modal keinen Mehrwert bringen würde:
Wenn das Element, dass die Video-Preview enthält, breiter 479px ist, oder die Dokumentenbreite kleiner 640, dann wird das Video nach dem Klick direkt dort ersetzt, wo die Preview gezeigt wird; ansonsten geht es in einem Modal auf, wobei dort derzeit ggf. das o.a. css/max-width greift.

**Comment by xwolfde** [comment]
Grobe Idee zu der Steuerung des Modals:
Grob gedacht:

```[fauvideo .. modal=""]```

mit modal=  always (modal geht immer auf)
	= auto (=default, wie jetzt)
	= no (kein Modal, nie)
	= NNNpx  (Wenn die Browserfenstergröße größer als NNN px ist)

**Comment by xwolfde** [comment]
mit v3 obsolet
