### ISSUE TITLE
Parameter width/height mit align (left, right, center)?

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-video#48]
Die aktuelle Version macht ja das Embed auf die vorhandene Maximalgröße.
Um es zu verkleinern muss man ein div drum herum machen, welches ein Inline-Style setzt oder eine Bootstrap-Klasse nutzt.

Macht es SInn, stattdessen doch wieder die Shortcode Attribut width/height anzugeben (bzw. nur eine davon um die Dimension aufrecht zu erhalten)?
Und dann zusätzlich um ein umrandendes Div zu sparen auch ein Alignment-Parameter zu haben?

**Comment by cassandre** [comment]
+1
Siehe auch https://gitlab.rrze.fau.de/rrze-webteam/FAU-Events/issues/36

**Comment by xwolfde** [comment]
Ist so nicht umsetzbar, da das Skript vorher nicht weiß, was für ein Video zurückgegeben wird.
Eine Einschränkung der Größe macht unter responsiblen Bedingungen nur SInn, wenn sie durch ein Grid außerhalb des Videocontents geschieht. Das Video wird jedoch immer 100% der verfügbaren Size einnehmen.
