### ISSUE TITLE
Scripts erst enqueuen, wenn sie gebraucht werden

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-video#6]
Das Plugin läd seine ganzen JS-Files (3 verschiedene) und CSS grundsätzlich immer und auf jeder Seite, auch wenn es gar nicht auf der Seite verwendet wird.
Außerdem wird im Code auch immer Inline-JS ergänzt.

Das ganze kostet Performance-Punkte :(

Bitte dies ändern, so daß Scripts nur dann enqueued werden, wenn sie auf der Webseite tatsächlich benötigt werden.

Abschaubeispiel: RRZE RSS Plugin (im Gitlab)

**Comment by bmehler** [comment]
Die Dateien werden nun im Shortcode und Widget geladen.
Inline-JS muss ich mir noch anschauen.

**Comment by xwolfde** [comment]
Es ist wieder drin!
Das JS wird geladen, wenn gar kein Video da ist.

**Comment by rvdforst** [comment]
Hab gerade das Skript überprüft und die "enqueue" der JS wird nur durchgeführt, wenn der Shortcode im Inhalt des Posts vorhanden ist oder das entsprechende Widget aktiviert ist. Kannst du mir den Link schicken, wo das Problem auftritt?

**Comment by xwolfde** [comment]
#25 und #26
