### ISSUE TITLE
show_video_columns() führt zu doppelt nebeneinander angezeigten IDs in RRZE-FAQ 

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-video#67]
Bitte in rrze-video-admin-view.php anstelle der Action 'manage_posts_custom_column' die Action 'manage_video_posts_custom_column' nutzen, da ansonsten alle anderen Plugins bzw post_types davon ebenso betroffen sind. 

Zeile 61:
anstatt

add_action('manage_posts_custom_column',  'RRZE\PostVideo\show_video_columns');

diese verwenden:

add_action('manage_video_posts_custom_column',  'RRZE\PostVideo\show_video_columns');

(Betrifft aktuell RRZE-FAQ - siehe https://github.com/RRZE-Webteam/rrze-faq/issues/58 )

**Comment by xwolfde** [comment]
ja. Im Branch mit der Umstellung wird das alles entfernt und renoviert..
Dies wird mit dem Update behoben sein.

**Comment by xwolfde** [comment]
im dev
