### ISSUE TITLE
Gruppenausgabe einer Kategorie

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-video#72]
Überlegen ob man eine Gruppe an Videos ausgeben will. Z.B. eine eigene Sammlung.

Hier wäre aber ggf. auch die Reihenfolge wichtig.

**Comment by lukasniebler** [comment]
Ich denke das nutzt eh niemand. Für Sammlungen sollten die Leute das Kurs-Feature des Videoportals nutzen. (Mir ist heute erst wieder eingefallen, dass es die Videothek-Funktion überhaupt noch gibt...)

Ich lass es mal offen für die Zukunft.

**Comment by lukasniebler** [comment]
Vorerst auf Eis gelegt. ServerSideRender sorgt ansonsten für Performance Probleme.
