### ISSUE TITLE
Videoportal Player Offset URLs

### ISSUE THREAD

**Issue by stefanosgeo** [RRZE-Webteam/rrze-video#84]
JWPlayer an fau.tv unterstützt seit version 3.12.107 ein URL offset  z.B. https://www.fau.tv/clip/id/27732/#offset=10m10s

Parameter

*url/#offset=XhYmZs*

weitere Beispiele:

* clip_url/#offset=10m10s -> spring zum 10 Minute 10 Sekunde

* clip_url/#offset=1h1m -> spring zum 1 Stunde 1 Min

* clip_url/#offset=2h05m30s-> spring zum 2 Stunden 5 Min 20 Sekunde

Der Player ist, , [laut Browser Regelungen](https://wordpress.org/support/topic/video-autoplay-is-mute-automatically-using-jwplayer/), gemutet

**Comment by xwolfde** [comment]
Ja...nur... dieses Plugin nutzt ja den JWPlayer nicht?

**Comment by stefanosgeo** [comment]
Ja ja mein Fehler..Das Video Plugin verwendet den API. 

Sorry für die Verwirrung
