### ISSUE TITLE
Feature Request: Option um Video-Autostart mit erzwungener Audio-Stummschaltung ab 0 Sekunden zu aktivieren

### ISSUE THREAD

**Issue by jbhs** [RRZE-Webteam/rrze-video#85]
Wünschenswert wäre, wenn über Parameter im Shortcode der Autostart des Videos aktiviert werden könnte und das Video per Default auf Stumm geschaltet werden könnte.

**Comment by xwolfde** [comment]
Nope. Wir sind zur Barrierefreiheit verpflichtet.
Ein Autostart eines Videos auf einer Website stellt ein Verstoß der entsprechenden Norm da, so dass ein Anbieten einer solchen Funktion dabei helfen würde, Menschen zu diskriminieren.

**Comment by jbhs** [comment]
Hallo Herr Wiese, vielen Dank für Ihre Antwort. Mal davon abgesehen, das es für viele Menschen nervig sein kann, wenn ein Video einfach so losläuft, auch wenn das lautlos ist. Sehe ich gerade nicht die Einschränkungen bei der Barrierefreiheit und bitte um Ihre Darstellung.

Ich konnte diesbezüglich auch keine Informationen bei der [WIA des W3C finden](https://www.w3.org/WAI/media/av/). Mich würde interessieren auf welche Norm Sie sich stützen und ob das viel größere Problem nicht die fehlenden Captions/Subtitles sind.

**Comment by xwolfde** [comment]
Siehe:
https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=142#audio-control

Ein Autoplay wäre nur denkbar, wenn es nur 3 Sekunden andauern würde oder man unmittelbare Stop-Möglichkeiten hätte.
Dies kann aber nicht garantiert werden, da das Plugin auch auf langen Seiten eingesetzt werden kann, wo das Video und damit dessen Bedienelemente nicht unmittelbar im Fokus sind.

Unser Norm ist natürlich die EN 301 549 V2.1.2  und somit alle Level A und Level AA - Erfolgskriterien der WCAG 2.1 als Mindestanforderung.

**Comment by jbhs** [comment]
_"If any audio on a Web page plays automatically for more than 3 seconds, either a mechanism is available to pause or stop the audio, or a mechanism is available to control audio volume independently from the overall system volume level._ Bezieht sich jedoch nur auf die Audiowiedergabe und nicht auf die Videowiedergabe.

Eine Autoplayoption für ein Video mit automatisch abgeschabtem Ton innerhalb von 0 Sekunden ist somit weiterhin kein Problem und würde das Erfolgskriterium 1.4.2 der WCAG 2.1 nicht verletzten.

Ich werde den Feature Request konkretisieren.

**Comment by xwolfde** [comment]
Leichter wäre es, einfach einen eigenen Branch zu machen ;)
Der Plyr bietet die Option ja nativ mit. Einfach die Fields zur Steuerung ergänzen und gut ist.
Für unseren Einsatzgebiet, also unserem Branch werde ich die Option jedoch nicht zulassen.

**Comment by xwolfde** [comment]
Im Nachhinein sehe ich, dass meine Antwort etwas kurzbündig sind und nicht so ganz auf die HIntergründe und Erwägungen eingehen, die auch eine Rolle spielen.
Deswegen (ohne jetzt ausarten zu wollen, eine kurze Erläuterung):

In der Tat würde für sich genommen und bei EInhaltung genau der Bedingungen die in https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=142 (und https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=142%2C148#low-or-no-background-audio) beschrieben sind, ein Autoplay eines Videos zulässig sein:
Kurz: Es wäre zulässig, wenn das Video keinen Ton abspielt und man eine unmittelbar zugänglichen Stopp-Schalter hätte, wenn es länger ist asl 3 Sekunden.

Soweit so richtig.
Der Punkt ist aber: Wann wird man genau diese Situation erfüllen (können)? Meiner Ansicht nach, wird dies nur der Fall sein können, wenn man eben ein entsprechendes Video vorbereitet hat und es an einer Stelle in der Webseite eingebunden ist, dass der Player ganz oben und also sofort sichtbar ist.
Jetzt ist es aber so, dass unsere Websites in der Desktopansicht bereits ca. 260 Pixel Offset vom Kopfteil haben. Von daher müsste ein Video bei Nutzung eines Templates schon sofort als erstes im Content gesetzt sein. 
(Oder aber, wir müssten den Player zusätzlich auch noch so erweitern, dass bei Anwahl der Option Autoplay ein "Stopp-"Schalteroverlay beim Laden der Seite sofort augenfällig sichtbar wird.)
Also alles schonmal mit viel Wenn und Abers verbunden. Jedoch lösbar!

Ich gehe aber davon aus, dass die Mehrheit der Autoren eben diese Bedingungen nicht erfüllen werden. Und damit werden sie dann genau gegen die WCAG verstoßen - mit unserer Hilfe, weil wir die Funktion bereit gestellt haben. Und das führt mich zu dem nächsten Abwägungsgrund:

Das Plugin wird ja nunmal für alle Websiten der Uni zur Verfügung gestellt. Derzeit sind dies ca. 700 WordPress-Sites, die es aktivieren können. Die überwiegende Mehrheit der lokalen Admins und Autoren sind keine IT-Leute und auch keine ausgebildeten Webredakteure. Die Mehrheit machen Mitarbeiter:innen aus Lehrstuhlsekretariaten und zeitlich befristete Wissenschaftler aus, die die Website "nebenher" pflegen müssen.

Der Player ohne die gewünschte Option sorgt -abseits der im Video allermeist mangelnden Audiotranskription an der wir nichts tun können- nun dafür, dass der Seitenautor sich keine Gedanken machen muss. Er gibt einfach nur die URL als Option ein und alles ist gut. (Und es gibt schon Autoren, die allein daran scheitern).

Wenn wir jetzt aber unter diesem Kontext eine Autoplay-Option anbieten, wieviele Autoren werden sich dann wohl Gedanken darüber machen, was sei damit bewirken und unter welchen Betriebsbedingungen das Video dann positioniert und auch lautlos gestellt werden muss?
Meiner Erfahrung nach wird hierüber in der Regel nicht gedacht. Die Autoren wollen -und das ist auch richtig und berechtigt- Content online bringen. Möglichst mit einer flachen Lernkurve ohne all das notwendige Hintergrundwissen. Ohne Notwendigkeit die WCAG 2.1 auch nur zu kennen!
Unter dieser Haltung sind fast alle Plugins und Themes aufgebaut: Sie müssen einen leichten Zugang für alle Autoren haben, damit die Autoren das tun können, was sie wirklich wollen: Content leicht und schnell online bringen.
Aus all den Plugins und Themes die wir seit Jahren machen, haben wir nun die Erfahrung gesammelt, das je mehr Optionen wir bieten, um so schwerer machen wir es der Masse der User - auch wenn sich einzelne, die genau diese oder jene Option wollten, sich freuen.
(Und das dies dann natürlich auf die Supporttickets Niederschlag findet, dürfte ja auch klar sein). 


tl;dr: Wir hier müssen stets die Waage halten zwischen Vielfältigen komplexen Lösungen und solchen, die beschränkt aber dafür einfach für jeden (auch Laien!) umsetzbar sind. Daher sind Umsetzung, wie das obige schwierig.

Ich hoffe jetzt dürfte klarer sein, warum ich so ablehnend bin und die Antwort so reduziert hab.


Ganz anders dagegen wäre ein Einsatz bei Webdesignern und Webentwicklern. Hier ist das Wissen da oder man kann es voraussetzen. Hier könnte man also auch erwarten, dass diese sich zu helfen wissen - und zum Beispiel WP selbst betreiben und ein Clon schreiben.
Und das ist ja auch einer der Gründe, warum wir hier mit unserem Zeug auf GitHub sind. Wir haben keine Probleme damit, wenn Agenturen oder Engagierte sich unseren Code holen und klonen und es in ihrem Sinne weiterentwickeln. Finde ich sogar gut. Noch besser, wenn es dann Merge-Requests zurück gibt. Noch besser, wenn jemand auch zeigt, dass meine EInschätzung zur Nutzbarkeit falsch war und es dann bei seiner/ihrer Website dann doch läuft (aber im Einsatz von den Autoren, nicht durch den Pro).
