### ISSUE TITLE
Frage: Title bei iFrame selber hinzufügen

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-video#89]
Bei Videos, die mit iFrame eingebunden werden (z.B. BR-Videos), zeigt mit Siteimprove einen Fehler an, weil kein "title" angegeben wird. Das macht ja deshalb Sinn, weil bei den iFrames keine Metadaten übernommen werden.

Deshalb meine Frage: Könnte man die Möglichkeit einrichten, in den Shortcode den Befehlt title="xyz" zu ergänzen, der dann als Metadaten für die Barrierefreiheit ausgegeben wird?

**Comment by lukasniebler** [comment]
Ist das weiterhin ein Problem?
