### ISSUE TITLE
Feature-Request: multiple CC files for a video from fau.tv

### ISSUE THREAD

**Issue by stefanosgeo** [RRZE-Webteam/rrze-video#91]
by the latest fau.tv update, API will provide links to additional transcripts if available

API example -> https://itunes.video.uni-erlangen.de/services/oembed/?url=https://www.fau.tv/webplayer/id/142573&format=json
JWPlayer example -> https://www.fau.tv/clip/id/39088

**Comment by lukasniebler** [comment]
In v3.4.6 (In Testphase)
