### ISSUE TITLE
Problem mit Meta-Tags bei Anführungszeichen im Video-Titel

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/rrze-video#93]
Anführungszeichen im Video-Titel werden nicht umgewandelt und zerschießen dadurch den html-Code der Meta-Tags:
![Bildschirmfoto 2022-01-24 um 12 49 51](https://user-images.githubusercontent.com/4435815/150777939-a8e813a4-d737-4285-97cc-dcaac860d31a.png)

Link zum Video (2 Minuten Wissen - "Nachgiebige" Roboter): https://www.youtube.com/watch?v=2xuZWkKkF34

**Comment by xwolfde** [comment]
fixed
